version: '3.8'

services:
  etl_monitoring:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./scripts:/app/scripts  # Persist scripts
      - ./raw:/app/raw  # Persist raw
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/random_user_sample
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: random_user_sample
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/raw

volumes:
  pg_data:
